### ISSUE TITLE
should prototypes be the same for bremove and binsert?

### ISSUE THREAD

**Issue by shawnlaffan** [perl5-utils/List-MoreUtils-XS#1]
The prototype for binsert includes a scalar, while that for bremove does not.  The documentation matches this situation, but it would be clearer for users if they were consistent, preferably using that for binsert so one can use any variable and not just the topic variable.  

Current:
```
bremove: PROTOTYPE: &\@
binsert: PROTOTYPE: &$\@
```

Suggested:
```
bremove: PROTOTYPE: &$\@
binsert: PROTOTYPE: &$\@
```

**Comment by shawnlaffan** [comment]
Sorry - just had a look at the test files so can see the reason for the difference now.  This can be closed.  

Some examples in the docs would be helpful for when these are included in a non-dev release.

**Comment by rehsack** [comment]
The documentation was and will be in List::MoreUtils only. Sorry for the inconvinience - but since List::MoreUtils::XS must be released before List::MoreUtils, watch out for the doc in https://github.com/perl5-utils/List-MoreUtils

**Comment by shawnlaffan** [comment]
That's fine - centralised docs are preferable in this case.
