### ISSUE TITLE
bremove in  version 0.420_001 does not remove anything when list has single item

### ISSUE THREAD

**Issue by shawnlaffan** [perl5-utils/List-MoreUtils-XS#2]
See code below.

```
use List::MoreUtils 0.420_001 qw /bremove/;
use Test::More tests => 1;

my @list = ('somestring');
my $target = $list[0];
is ($target, (bremove {$_ <=> $target} @list), 'removed from single item list');
```

**Comment by rehsack** [comment]
AvFILLp(av) == -1 for empty arrays - fixed in bremove & binsert, checking for other occurrences

**Comment by rehsack** [comment]
Maybe testing the latest release is preferred over testing -DEV releases from ages ago :)
My first reaction on the mail was: "wtf. should use 0.423". Beside my misbehavior - thanks for figuring that out and sharing the test. Let's see whether more comes or a new release can be shipped.

**Comment by shawnlaffan** [comment]
Thanks for the prompt fix. 

And sorry for the title.  It was the version from the latest List::MoreUtils, not List::MoreUtils::XS.  I was actually testing with L::MU::XS 0.422.
