### ISSUE TITLE
clang warning logical vs bitwise

### ISSUE THREAD

**Issue by bluhm** [perl5-utils/List-MoreUtils-XS#3]
When compiling List-MoreUtils-XS 0.423 with clang I get this warning:
<pre>
cc -c  -I.  -DNO_LOCALE_NUMERIC -DNO_LOCALE_COLLATE -fno-strict-aliasing -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 -I/usr/local/include -O2    -DVERSION=\"0.423\"  -DXS_VERSION=\"0.423\" -DPIC -fPIC  "-I/usr/libdata/perl5/amd64-openbsd/CORE"   XS.c
XS.xs:282:21: warning: logical not is only applied to the left hand side of this
      bitwise operator [-Wlogical-not-parentheses]
                if (!(PadnameFLAGS(name_sv)) & SVf_OK)
                    ^                        ~
XS.xs:282:21: note: add parentheses after the '!' to evaluate the bitwise
      operator first
                if (!(PadnameFLAGS(name_sv)) & SVf_OK)
                    ^
                     (                               )
XS.xs:282:21: note: add parentheses around left hand side expression to silence
      this warning
                if (!(PadnameFLAGS(name_sv)) & SVf_OK)
                    ^
                    (                       )
1 warning generated.
</pre>

The code does not look correct.  PadnameFLAGS is a bit field with
presumably some bits set.  After logical not the value is 0 and the
condition is never true.

**Comment by rehsack** [comment]
I took the code (as comment above shows) from Padwalker. I would appreciate when you open a ticket in RT since I forget Github issues regulary - but thanks for pointing that out, I take a deep look and will report.

**Comment by bluhm** [comment]
Created a Ticket in RT
https://rt.cpan.org/Public/Bug/Display.html?id=122883

**Comment by rehsack** [comment]
Thank you very much. I'm closing this here now.
