### ISSUE TITLE
warning: format '%ld' expects argument of type 'long int', but argument 2 has type 'IV {aka long long int}' [-Wformat=]

### ISSUE THREAD

**Issue by andreas-schwab** [perl5-utils/List-MoreUtils-XS#4]
XS.xs:2274:19: warning: format '%ld' expects argument of type 'long int', but argument 2 has type 'IV {aka long long int}' [-Wformat=]
             croak("Modification of non-creatable array value attempted, subscript %ld", idx);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#   Failed test at t/xs/part.t line 32.
#                   'Modification of non-creatable array value attempted, subscript 23296520 at t/xs/part.t line 30.
# '
#     doesn't match '(?^:^Modification of non-creatable array value attempted, subscript -1)'
# Looks like you failed 1 test of 28.
t/xs/part.t ................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/28 subtests

**Comment by rehsack** [comment]
Which version of List::MoreUtils::XS are you using?

**Comment by andreas-schwab** [comment]
0.421

**Comment by rehsack** [comment]
Please use 0.423

**Comment by andreas-schwab** [comment]
Same error.

**Comment by rehsack** [comment]
Okay ;)

Now you can apply https://github.com/perl5-utils/List-MoreUtils-XS/commit/5a762544a521bee9cf4a0ad59fab6664d6ba3fda and kindly report whether it changes the situation. In that case I need to modify the commit message ;)

**Comment by andreas-schwab** [comment]
That works.

**Comment by rehsack** [comment]
0.425_001 is on it's way to CPAN. Try it, send test reports and sooner or later a release for the masses will be out.
