### ISSUE TITLE
warning: operation on 'count' may be undefined [-Wsequence-point]

### ISSUE THREAD

**Issue by andreas-schwab** [perl5-utils/List-MoreUtils-XS#5]
In file included from /usr/lib/perl5/5.24.1/ppc-linux-thread-multi-64int/CORE/perl.h:5615:0,
                 from XS.xs:34:
XS.xs: In function 'XS_List__MoreUtils__XS_mode':
XS.xs:2078:20: warning: operation on 'count' may be undefined [-Wsequence-point]
         EXTEND(SP, ++count);
/usr/lib/perl5/5.24.1/ppc-linux-thread-multi-64int/CORE/embed.h:574:53: note: in definition of macro 'stack_grow'
 #define stack_grow(a,b,c) Perl_stack_grow(aTHX_ a,b,c)
                                                     ^
/usr/lib/perl5/5.24.1/ppc-linux-thread-multi-64int/CORE/pp.h:372:49: note: in expansion of macro '_EXTEND_SAFE_N'
                            sp = stack_grow(sp,p,_EXTEND_SAFE_N(n));     \
                                                 ^~~~~~~~~~~~~~
XS.xs:2078:9: note: in expansion of macro 'EXTEND'
         EXTEND(SP, ++count);
         ^~~~~~

**Comment by rehsack** [comment]
From my point of view, https://github.com/perl5-utils/List-MoreUtils-XS/blob/master/XS.xs#L2078 initializes count. And https://github.com/perl5-utils/List-MoreUtils-XS/blob/master/XS.xs#L450-L475 does not "deinitialize" it.

Can you please be more clear where count is used uninitialized?

**Comment by andreas-schwab** [comment]
What uninitialized?

**Comment by rehsack** [comment]
You can try following patch:

    diff --git a/XS.xs b/XS.xs
    index 063aa27..e482d87 100644
    --- a/XS.xs
    +++ b/XS.xs
    @@ -2114,7 +2114,8 @@ CODE:

         if(seen_undef == max)
         {
    -        EXTEND(SP, ++count);
    +       ++count;
    +        EXTEND(SP, count);
             ST(count-1) = &PL_sv_undef;
         }

**Comment by rehsack** [comment]
Aaaand? ;)

**Comment by andreas-schwab** [comment]
https://build.opensuse.org/package/show/home:Andreas_Schwab:Factory/perl-List-MoreUtils-XS

**Comment by rehsack** [comment]
0.425_001 is on it's way to CPAN. Try it, send test reports and sooner or later a release for the masses will be out.
