### ISSUE TITLE
XSLoader version dependency is unnecessarily high

### ISSUE THREAD

**Issue by DrHyde** [perl5-utils/List-MoreUtils-XS#6]
Deep in a mess of dependencies on perl 5.8 I've hit a problem installing this dist:

    Warning: prerequisite XSLoader 0.22 not found. We have 0.02.

Unfortunately more modern XSLoader doesn't like Ye Olde Perle and won't build. But if I ignore that warning above and try to 'make' and 'make test' anyway, all the tests pass. So unless there's some pressing reason for depending specifically on 0.22 or higher that I'm missing, It would be good if you could relax the version requirement.

**Comment by rehsack** [comment]
I'm sorry to tell you, but you're mislead. Please see https://rt.cpan.org/Ticket/Display.html?id=115808 for details.

**Comment by rehsack** [comment]
And by the way:
ernie:~ sno$ perlbrew use 5.8.1
ernie:~ sno$ perl -MXSLoader -le 'print XSLoader->VERSION'
0.24

So - what kind of problems XSLoader seems to have - they're probably not a perl-5.8.1 problem, it's probably a PEBCAK. Judge with care.

**Comment by DrHyde** [comment]
It's possibly OS-specific. Anyway, if you've got a good reason for using a later version, so be it.

**Comment by rehsack** [comment]
It shouldn't - I have it on Linux and MacOS. If you have a serious XSLoader issue with 5.8 - open a ticket, CC me and I support where I can to get it fixed. No one should have an XSLoader before 0.22 because of the possible injection of evil code.
